# Generated by Django 3.0.2 on 2020-06-02 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 2, 55, 14, 586941, tzinfo=utc), verbose_name='create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
