# Generated by Django 3.0.7 on 2020-06-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
