# Generated by Django 3.0.7 on 2020-06-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_blog', '0002_auto_20200610_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
